url.hostBaseUrl= https://provider.doctorglobe.com
url.healthcareproviderBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider
url.amenityBaseUrl = http://localhost:8080/dg-host-data/rest/amenity
url.healthcareproviderAmenityBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-amenity
url.cuisineBaseUrl = http://localhost:8080/dg-host-data/rest/cuisine
url.healthcareproviderCuisineBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-cuisine
url.equipmentBaseUrl = http://localhost:8080/dg-host-data/rest/equipment
url.healthcareproviderEquipmentBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-equipment
url.accreditationBaseUrl = http://localhost:8080/dg-host-data/rest/accreditation
url.healthcareproviderAccreditationBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-accreditation
url.healthcareprovidertypeBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovidertype
url.healthcareproviderHealthcareprovidertypeBaseUrl =  http://localhost:8080/dg-host-data/rest/healthcareprovider-healthcareprovidertype
url.featureBaseUrl = http://localhost:8080/dg-host-data/rest/feature
url.healthcareproviderunitBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareproviderunit
url.healthcareproviderUnitFeatureBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-unit-feature
url.insuranceBaseUrl = http://localhost:8080/dg-host-data/rest/insurance
url.healthcareproviderInsuranceBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-insurance
url.countryBaseUrl = http://localhost:8080/dg-host-data/rest/country
url.stateBaseUrl = http://localhost:8080/dg-host-data/rest/state
url.cityBaseUrl = http://localhost:8080/dg-host-data/rest/city
url.chainBaseUrl = http://localhost:8080/dg-host-data/rest/chain
url.ratingcompaniesBaseUrl = http://localhost:8080/dg-host-data/rest/ratingcompanies
url.healthcareproviderRatingsBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-ratings
url.healthcareproviderLanguageBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-language
url.healthcareproviderPhotoBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareproviderphoto
url.specialtyBaseUrl = http://localhost:8080/dg-host-data/rest/specialty
url.specialtyTreatmentBaseUrl = http://localhost:8080/dg-host-data/rest/specialty-treatment
url.healthcareproviderSpecialtyBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-specialty
url.healthcareproviderSpecialtyPractitionerBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-specialty-practitioner
url.healthcareproviderSpecialtyTreatmentMethodBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-specialty-treatment-method
url.healthcareproviderSpecialtyTreatmentMethodPractitionerBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-specialty-treatment-method-practitioner
url.healthcareproviderSpecialtyTreatmentMethodPractitionerStatBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-specialty-treatment-method-practitioner-stat
url.treatmentBaseUrl = http://localhost:8080/dg-host-data/rest/treatment
url.methodBaseUrl = http://localhost:8080/dg-host-data/rest/method
url.practitionerBaseUrl = http://localhost:8080/dg-host-data/rest/practitioner
url.practitionerLanguageBaseUrl = http://localhost:8080/dg-host-data/rest/practitioner-language
url.practitionertypeBaseUrl = http://localhost:8080/dg-host-data/rest/practitionertype
url.attestationsBaseUrl = http://localhost:8080/dg-host-data/rest/attestations
url.attestationsPractitionerBaseUrl = http://localhost:8080/dg-host-data/rest/attestations-practitioner
url.aclRolesBaseUrl = http://localhost:8080/dg-host-data/rest/acl-roles
url.statsBaseUrl = http://localhost:8080/dg-host-data/rest/stats
url.userBaseUrl = http://localhost:8080/dg-host-data/rest/user
url.healthcareproviderPractitionerBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-practitioner
url.mediaBaseUrl = http://localhost:8080/dg-host-media/rest/file
url.loginUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-user
url.imageResourceUrl= https://provider.doctorglobe.com
url.corporatecompanyInsuranceBaseUrl = http://localhost:8080/dg-host-data/rest/corporatecompany-insurance

url.filepath = file:/DoctorGlobe/
url.uploadPath = /DoctorGlobe
url.doctorfilepath = file:/DoctorGlobe/

#mail config
mail.server.host=smtpout.secureserver.net
mail.server.port=25
mail.server.username=admin@doctorglobe.com
mail.server.password=d0ct0rg10b_
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.debug = true
mail.from = admin@doctorglobe.com
