url.practitioner=practitioner/
url.patient=patient/
url.patientCase=patientcase/
url.patientBase=http://localhost:8080/data/rest/patient
url.patientCaseBase=http://localhost:8080/data/rest/patientcase
url.patientConferenceBase=http://localhost:8080/data/rest/patientconference
url.patientCaseBookingBase=http://localhost:8080/data/rest/patientcasebooking
url.patientCaseFileBase=http://localhost:8080/data/rest/patientcasefile
url.practitionerBase=http://localhost:8080/data/rest/practitioner/
url.practitionertypeBase=http://localhost:8080/data/rest/practitionertype/
url.loginUrl = http://localhost:8080/data/rest/practitioner/get/email/
url.patientCaseMessagesBase=http://localhost:8080/data/rest/patientcasemessages
url.host=http://localhost:8080/doctor

url.patientMailUrl = http://localhost:8080/patient/user/discussion?pc=
url.practitionerMailUrl = http://localhost:8080/doctor

url.practitionerNewMessages = http://localhost:8080/doctor/totalnewmessage
url.countryBaseUrl = http://localhost:8080/data/rest/country
url.stateBaseUrl = http://localhost:8080/data/rest/state
url.cityBaseUrl = http://localhost:8080/data/rest/city
url.imageResourceUrl=http://104.131.12.189:8080/dg-host-doctor

url.filepath = file:/tmp/
url.uploadPath = /tmp

mail.server.host=smtpout.secureserver.net
mail.server.port=25
mail.server.username=admin@doctorglobe.com
mail.server.password=d0ct0rg10b_
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.debug = true
mail.from = admin@doctorglobe.com