url.base=http://localhost:8080/dg-host-data/rest/search/
url.healthcareprovider=healthcareprovider/
url.practitioner=practitioner/
url.treatment=treatment/
url.patient=patient/
url.patientCase=patientcase/
url.practitionerBase=http://localhost:8080/dg-host-data/rest/practitioner
url.patientBase=http://localhost:8080/dg-host-data/rest/patient
url.patientCaseBase=http://localhost:8080/dg-host-data/rest/patientcase
url.patientConferenceBase=http://localhost:8080/dg-host-data/rest/patientconference
url.solr=http://localhost:8983/solr/select
url.host=https://user.doctorglobe.com/
url.patientCaseBookingBase=http://localhost:8080/dg-host-data/rest/patientcasebooking
url.patientCaseFileBase=http://localhost:8080/dg-host-data/rest/patientcasefile
url.autocomplete=https://user.doctorglobe.com/autocomplete/search

url.customerMailUrl = https://user.doctorglobe.com
url.imageUrl = /resources/uploads/patient/
url.loginUrl = http://localhost:8080/dg-host-data/rest/patient/get/email/
url.patientCaseMessagesBase=http://localhost:8080/dg-host-data/rest/patientcasemessages
url.cityBase=http://localhost:8080/dg-host-data/rest/city
url.stateBase=http://localhost:8080/dg-host-data/rest/state
url.countryBase=http://localhost:8080/dg-host-data/rest/country
url.patientMailUrl = https://user.doctorglobe.com/user/discussion?pc=
url.practitionerMailUrl = http://localhost:8080/dg-host-doctor/home/view?pc=
url.employeeCorporatecompanyBase=http://localhost:8080/dg-host-data/rest/employee-corporatecompany
url.treatmentPriceBase=http://localhost:8080/dg-host-data/rest/treatment-price
url.treatmentDocumentBase=http://localhost:8080/dg-host-data/rest/treatment-document
url.treatmentQuestionnaireBase=http://localhost:8080/dg-host-data/rest/treatment-questionnaire
url.patientcaseTreatmentQuestionnaireBase=http://localhost:8080/dg-host-data/rest/patientcase-treatment-questionnaire
url.documentBase=http://localhost:8080/dg-host-data/rest/document
url.patientcasePriceBase=http://localhost:8080/dg-host-data/rest/patientcase-price
url.imageResourceUrl= https://user.doctorglobe.com

url.patientNewMessages = https://user.doctorglobe.com/totalnewmessage
url.filepath = file:/DoctorGlobe/
url.hospitalfilepath = file:/DoctorGlobe/
url.doctorfilepath = file:/DoctorGlobe/
url.uploadPath = /DoctorGlobe

case.conference.limit = 2
currency = USD
mail.server.host=smtpout.secureserver.net
mail.server.port=25
mail.server.username=admin@doctorglobe.com
mail.server.password=d0ct0rg10b_
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.debug = true
mail.from = admin@doctorglobe.com
