practitioner.rating.price.weightage = 35
practitioner.rating.number_performed_last_year.weightage = 25
practitioner.rating.corrections_last_year.weightage = 10
practitioner.rating.us_trained.weightage = 10
practitioner.rating.us_certified.weightage = 10
practitioner.rating.english_speaking.weightage = 5
practitioner.rating.insurance_cap.weightage = 5

healthcareprovider.rating.top_practitioner_rating.weightage = 35
healthcareprovider.rating.location.weightage = 0
healthcareprovider.rating.distance.weightage = 40
healthcareprovider.rating.average_practitioner_rating.weightage = 10
healthcareprovider.rating.insurance_cap.weightage = 5
healthcareprovider.rating.amenities.weightage = 3
healthcareprovider.rating.equipment.weightage = 2
healthcareprovider.rating.us_affiliation.weightage = 3
healthcareprovider.rating.mortality_rate.weightage = 2


ranking.distanceWeight = 0.5
ranking.bonusWeight = 0.25
ranking.volumeWeight = 0.25