environment = production
url.base=http://localhost:8080/dg-host-data/rest/search/
url.healthcareprovider=healthcareprovider/
url.practitioner=practitioner/
url.treatment=treatment/
url.patient=patient/
url.patientCase=patientcase/
url.practitionerBase=http://localhost:8080/dg-host-data/rest/practitioner
url.patientBase=http://localhost:8080/dg-host-data/rest/patient
url.patientCaseBase=http://localhost:8080/dg-host-data/rest/patientcase
url.patientConferenceBase=http://localhost:8080/dg-host-data/rest/patientconference
url.solr=http://localhost:8983/solr/select
url.host=https://user.doctorglobe.com/
url.patientCaseBookingBase=http://localhost:8080/dg-host-data/rest/patientcasebooking
url.patientCaseFileBase=http://localhost:8080/dg-host-data/rest/patientcasefile
url.autocomplete=https://user.doctorglobe.com/autocomplete/search

url.customerMailUrl = https://user.doctorglobe.com
url.imageUrl = /resources/uploads/patient/
url.loginUrl = http://localhost:8080/dg-host-data/rest/patient/get/email/
url.patientCaseMessagesBase=http://localhost:8080/dg-host-data/rest/patientcasemessages
url.cityBase=http://localhost:8080/dg-host-data/rest/city
url.stateBase=http://localhost:8080/dg-host-data/rest/state
url.countryBase=http://localhost:8080/dg-host-data/rest/country
url.patientMailUrl = https://user.doctorglobe.com/user/discussion?pc=
url.practitionerMailUrl = http://localhost:8080/dg-host-doctor/home/view?pc=
url.employeeCorporatecompanyBase=http://localhost:8080/dg-host-data/rest/employee-corporatecompany
url.treatmentPriceBase=http://localhost:8080/dg-host-data/rest/treatment-price
url.treatmentDocumentBase=http://localhost:8080/dg-host-data/rest/treatment-document
url.treatmentQuestionnaireBase=http://localhost:8080/dg-host-data/rest/treatment-questionnaire
url.patientcaseTreatmentQuestionnaireBase=http://localhost:8080/dg-host-data/rest/patientcase-treatment-questionnaire
url.documentBase=http://localhost:8080/dg-host-data/rest/document
url.patientcasePriceBase=http://localhost:8080/dg-host-data/rest/patientcase-price
url.imageResourceUrl= https://user.doctorglobe.com
url.associateUrl = http://localhost:8080/dg-host-data/rest/associate/get/email/
url.associateBaseUrl = http://localhost:8080/dg-host-data/rest/associate
url.associationBaseUrl = http://localhost:8080/dg-host-data/rest/association
url.corporatecompanyBaseUrl = http://localhost:8080/dg-host-data/rest/corporate-company
url.healthcareproviderSpecialtyTreatmentMethodBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-specialty-treatment-method
url.healthcareproviderSpecialtyTreatmentMethodPractitionerBaseUrl = http://localhost:8080/dg-host-data/rest/healthcareprovider-specialty-treatment-method-practitioner
url.treatmentBaseUrl = http://localhost:8080/dg-host-data/rest/treatment
url.apiUserBaseUrl=http://localhost:8080/dg-host-data/rest/api-user

url.patientNewMessages = https://user.doctorglobe.com/totalnewmessage
url.filepath = file:/DoctorGlobe/
url.hospitalfilepath = file:/DoctorGlobe/
url.doctorfilepath = file:/DoctorGlobe/
url.uploadPath = /DoctorGlobe
resultLimit = 10
case.conference.limit = 1000
currency = USD
ratingUrl = http://health.usnews.com/best-hospitals/area/

minimumDistanceForAirTravel = 200
minimumDistanceForHotel = 100
domesticFlightCost = 500
internationalFlightCost = 500
taxiCostPerMileToHospital = 2

ranking.distanceWeight = 0.6
ranking.bonusWeight = 0.1
ranking.volumeWeight = 0.3

minimumHospitalNumForOriginPrice = 5
originRadius = 30

broker.user.pagination.limit = 10
user.profile.show = 1
user.myarea.show = 0

mail.server.host=smtpout.secureserver.net
mail.server.port=25
mail.server.username=support@surgerate.com
mail.server.password=Tb2355627
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.debug = true
mail.from = support@surgerate.com
